###Commodities
names_commodities <- rbind(
  c("Produits de l'agriculture, de la chasse et de la pêche",'cagr'),
  c("Produits sylvicoles",'cfor'),
  c("Produits alimentaires et boissons",'cfoo'),
  c("Véhicules automobiles, remorques et semi-remorques",'cveh'),
  c("Minéraux non-métalliques",'cgla'),
  c("Papier et carton",'cpap'),
  c("Produits chimiques",'cche'),
  c("Produits en caoutchouc et en plastique",'cpla'),
  c("Produits métallurgiques",'cmet'),
  c("Autres produits pour l'industrie",'cigo'),
  c("Autres produits de consommation",'ccgo'),
  c("Construction de bâtiments et de génie civil",'ccon'),
  c("Transport ferroviaire",'srai'),
  c("Transport routier",'croa'),
  c("Transport fluvial",'cwat'),
  c("Transport aérien",'cair'),
  c("Services privés",'cpri'),
  c("Services publics",'cpub'),
  c("Produit des industries extractives",'cmin'),
  c("Charbon et produits du charbon",'ccoa'),
  c("Pétrole brut",'ccoi'),
  c("Carburants",'cfut'),
  c("Fuel domestique",'cfuh'),
  c("Gaz naturel",'cgas'),
  c("Électricité",'cele'),
  c("Chaleur",'chea'),
  c("Biomasse",'cbio'),
  c("Autres énergies",'cote'),
  c("Agriculture",'C001'),
  c("Industrie Energético-intensives",'C002'),
  c("Autres industries",'C003'),
  c("Construction",'C004'),
  c("Transport",'C005'),
  c("Services",'C006'),
  c("Énergie de source fossile",'C007'),
  c("Autres énergies",'C008')
) %>%
  as.data.frame() %>% rename(name = V1,code = V2)

###Sectors
names_sectors <- rbind(
  c("Agriculture et pêche",'sagr'),
  c("Sylviculture et exploitation forestière",'sfor'),
  c("Industries alimentaires",'sfoo'),
  c("Industries automobiles",'sveh'),
  c("Fabrication d'autres produits minéraux non métalliques",'sgla'),
  c("Manufacture of paper and paperboard",'spap'),
  c("Manufacture of chemicals",'sche'),
  c("Fabrication de produits en caoutchouc et en plastique",'spla'),
  c("Métallurgie",'smet'),
  c("Manufacture d'autres biens pour l'industrie",'sigo'),
  c("Manufacture d'autres biens de consommation",'scgo'),
  c("Construction de batîments et du génie civil",'scon'),
  c("Transport ferroviaire",'srai'),
  c("Transport routier",'sroa'),
  c("Transport fluvial",'swat'),
  c("Transport aérien",'sair'),
  c("Services privés",'spri'),
  c("Services publics",'spub'),
  c("Activités extractives",'smin'),
  c("Production de pétrole raffiné",'soil'),
  c("Production de biofuel",'sbfu'),
  c("Production de gaz naturel",'sgas'),
  c("Production et distribution de biogaz",'sbga'),
  c("Production d'électricité par nucléaire",'senu'),
  c("Production d'électricité par centrale à fuel",'seoi'),
  c("Production d'électricité par centrale à fuel",'sega'),
  c("Production d'électricité par centrale à gaz",'seco'),
  c("Production d'électricité par centrale éolienne",'sewi'),
  c("Production d'électricité par centrale solaire",'seso'),
  c("Production d'électricité par centrale hydraulique",'sehy'),
  c("Cogénération (CHP) et production d'électricité par source de chaleur",'sech'),
  c("Électricité-autres",'seot'),
  c("Agriculture",'S001'),
  c("Industrie Energético-intensives",'S002'),
  c("Autres industries",'S003'),
  c("Construction",'S004'),
  c("Transport",'S005'),
  c("Services",'S006'),
  c("Énergie de source fossile",'S007'),
  c("Autres énergies",'S008')
) %>%
  as.data.frame() %>% rename(name = V1,code = V2)
