---
title: "Sensitivity Shock G"
author: "Maryème"
format: revealjs
params:
  startyear: 2020
  endyear: 2100
  template_default: ofce
  classification: c0_s0
  version_publi: false
  recreate_price_data: true
  project_name: sensitivity_shock_g
---


```{r setup, include=FALSE}
#| label: setup
#| include: false


knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)

path_main <-  stringr::str_remove(getwd(), "results/report/markdown")

redirect <- function(normal_path, redirect = path_main){
  if(is.null(redirect)){
    res <- file.path(normal_path)  
  }else{
    res <- file.path(paste0(redirect), normal_path)  
  }
  
  res |>  normalizePath()
}


startyear <- params$startyear
endyear <- params$endyear
template_default <- params$template_default
classification <- params$classification
project_name <- params$project_name


library(glue)
source(redirect("src/functions.R"))
purrr::map(list.files(redirect("/src/functions_src/")),
           ~source(file.path(redirect("/src/functions_src/"),.x)))
library(Unicode)
library(plotly)

## Options

options(ofce.base_family = "Arial")


## Diverse imports
data_full<-readRDS(file = redirect(file.path("data","output",str_c(project_name,"_",classification,".rds"))))
```

```{r}

variable_macro <- c( "Y", "CH", "I", "G")
label_macro <- c("GDP", "Households consumption", "Investment", "Public spending")

A <- simpleplot(data_full,variable_macro, label_macro, startyear, endyear,  transformation = "reldiff", titleplot = " GDP and its components (in relative difference from baseline)",
           unit = "percent", decimal = 0.1 ,scenario = "shock_g_p_0.5_u_1.5_tra", name_baseline = "baseline_p_0.5_u_1.5_tra")
B <- simpleplot(data_full,variable_macro, label_macro, startyear, endyear,  transformation = "reldiff", titleplot = " GDP and its components (in relative difference from baseline)",
           unit = "percent", decimal = 0.1 ,scenario = "shock_g_p_0.5_u_0.5_tra", name_baseline = "baseline_p_0.5_u_0.5_tra")

ggarrange(A,B,
labels = c("(a)", "(b)"),
hjust = -0.5, vjust = 1.5,
ncol = 2, nrow = 1,
widths = 2,  heights = 1)


```




