---
title: "ThreeME code structure"
subtitle: "ThreeME training"
author: ""
date: ""
institute: ""
format: html
theme: OFCE
---

```{r libimport, echo = FALSE}
library(quarto)
library(DiagrammeR)
```

```{r attempt2, echo = FALSE}
DiagrammeR::mermaid("
graph LR
 A((main))-->D(configuration)
    D[configuration]-->D1(Configuration files: config_threeme.R, etc.)
    D[configuration]-->D2(scenarii_calib)
      D2(scenarii_calib)-->D21(Files for calibration of the shocks)
    D[configuration]-->D3(saved_configurations)
      D3(saved_configurations)-->D31(Advanced user: save the configuration parameter as config_DATE_USER.rds)

 A((main))-->E(results)
    E[results]-->E2(report)
      E2(report)-->E21(markdown: Quarto and R Markdown files)
      E2(report)-->E22(render:  results files generated with Markdown)
   E[results]-->E1(eviews)
      E1(eviews)-->E11(Advanced user: save results files generated with the Eviews solver)
 

 A((main))-->B(src)
    B[src]-->B1(model)
      B1(model)-->B11(model files.mdl)
    B[src]-->B2(bridges)
      B2(bridges)-->B21(Bridges defining the sectors/commodities aggregation for results)
    B[src]-->B4(functions_src)
      B4(functions_src)-->B41(Advanced user: In-house developed functions)
    B[src]-->B3(compiler)
      B3(compiler)-->B31(Advanced user: convert the equations and calibrations mdl files into input files for the solver)
    B[src]-->B5(development)
      B5(development)-->B51(Advanced user: functions under development)
    B[src]-->B7(R_solver_files)
      B7(R_solver_files)-->B71(Advanced user: scripts to run R solver)
    B[src]-->B8(Eviews)
      B8(Eviews)-->B81(Advanced user: scripts to run Eviews solver)
    B[src]-->B6(data, Archived_run_threeme_dependencies, compiler_py)
      B6(data)-->B61(Deprecated: will be deleted in future release)

 A((main))-->C(data)
    C[data]-->C1(input)
      C1(input)-->C11(Country data used for the calibration: .xlsx)
    C[data]-->C2(output)
      C2(output)-->C21(Advanced user: simulation result files: .rds)
    C[data]-->C3(temp)
      C3(temp)-->C31(Advanced user: temporary files generated by the solvers)

 A((main))-->F(user_guides)
    F(user_guides)-->F1(Documentation to run the model)
  ")
```